# Generated by Django 6.0.4 on 2026-05-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_notification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('authority', 'Authority'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='citizen', max_length=20),
        ),
    ]
