# Generated by Django 6.0.4 on 2026-05-13 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Anonymous', help_text='Display name shown in UI', max_length=100)),
                ('user_role', models.CharField(choices=[('guest', 'Guest'), ('citizen', 'Citizen'), ('authority', 'Authority'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='guest', help_text='Role badge shown next to comment', max_length=20)),
                ('content', models.TextField(help_text='Comment text content', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag for moderation')),
                ('issue', models.ForeignKey(help_text='The issue this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issues.issue')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment for nested replies (null = top-level)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='issues.comment')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user (null for anonymous guests)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['issue', 'parent', 'created_at'], name='comments_issue_i_c8c796_idx')],
            },
        ),
    ]
